# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Evan's Blog | An FE developer's Blog
subtitle:
description: With some fe dev skills blog writed by Evan
keywords:
  - javascript
  - es6
  - html
  - css
  - ga
  - gtm
  - react
  - unit test
  - gitlab
  - github
  - CI
author: evanhongyousan
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://evanhongyousan.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year/:month/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date
auto_excerpt:
  enable: true
  length: 150

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html

# deploy:
#   type: git
#   repo: https://github.com/EvanHongYousan/EvanHongYousan.github.io.git #https://bitbucket.org/JohnSmith/johnsmith.bitbucket.io
#   branch: master #published
#   message:

# repo: https://gitee.com/EvanHongYousan/EvanHongYousan.git #https://bitbucket.org/JohnSmith/johnsmith.bitbucket.io

deploy:
  type: git
  repo: git@github.com:EvanHongYousan/EvanHongYousan.github.io.git #https://bitbucket.org/JohnSmith/johnsmith.bitbucket.io
  branch: master #published
  message:

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true

feed: # RSS订阅插件
  type: atom
  path: atom.xml
  limit: 0

plugins: hexo-generate-feed

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true

# 图片懒加载
# hexo-lazyload-image
lazyload:
  enable: false
  onlypost: false
# 文章内容图片cdn配置，配合hexo-tag-asset-img插件
# asset_img_url: https://cdn.jsdelivr.net/gh/evanhongyousan/evanhongyousan.github.io

douban:
  user: 185733944
  builtin: false
  book:
    title: "Books"
    quote: "明天再看"
  movie:
    title: "Movies"
    quote: "看完这集就学习去"
  game:
    title: "Games"
    quote: "再打半小时就学习去"
  timeout: 10000

steam:
  enable: true
  steamId: "76561198254399899" #steam 64位Id
  path: steamgames/index.html
  title: "Steam库存"
  quote: "赢一盘就睡！"
  tab: all # all 或 recent , all: 所有游戏, recent: 最近游玩的游戏
  length: 1000
  imgUrl: #'https://media.st.dl.pinyuncloud.com/steamcommunity/public/images/avatars/ec/eca67b9aa8f001bf7fd7fc99c32f92d45fabd0b3_full.jpg'
  proxy:
    host:
    port:

robotstxt:
  useragent: "*"
  disallow:
    - /js/
    - /css/
  allow:
    - /
  sitemap: /sitemap.xml

bangumi: # 追番设置
  enable: true
  path:
  vmid: 2899700
  title: '追番列表'
  quote: '生命不息，追番不止！'
  show: 1
  loading:
  metaColor:
  color:
  webp:
  progress:
  extra_options:
    key: value
cinema: # 追剧设置
  enable: true
  path:
  vmid: 2899700
  title: '放映厅列表'
  quote: '生命不息，追剧不止！'
  show: 1
  loading:
  metaColor:
  color:
  webp:
  progress:
  extra_options:
    key: value
