name: Blog CI

on: [push] # 当有新push时运行

# on:
#   push:
#     tags:
#       - '*'

env:
  TZ: Asia/Shanghai

jobs:
  deploy: # 一项叫做deploy的任务
    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行

    steps:
      - name: Checkout # 将仓库内master分支的内容下载到工作目录
        uses: actions/checkout@v1 # 脚本来自 https://github.com/actions/checkout

      - name: Use Node.js 10.x # 配置Node环境
        uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
        with:
          node-version: '10.x'

      - name: Setup Hexo env
        env:
          GITHUB_DEPLOY_KEY: ${{ secrets.blog_ci_rsa }}
        run: |
          # set up private key for deploy
          mkdir -p ~/.ssh/
          echo "$GITHUB_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置秘钥
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
          # set git infomation
          git config --global user.name 'EvanHongYousan' # 换成你自己的邮箱和名字
          git config --global user.email '1370204201@qq.com'
          # install dependencies
          npm i -g hexo-cli@3.9.0 # 安装hexo
          npm i

      - name: Deploy GitHub Page
        run: |
          # publish
          hexo bangumi -u && hexo cinema -u && hexo steam -u && hexo generate && hexo douban && hexo deploy # 执行部署程序

      # - name: Sync to Gitee
      #   uses: wearerequired/git-mirror-action@master
      #   env:
      #     # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
      #     SSH_PRIVATE_KEY: ${{ secrets.blog_ci_rsa }}
      #   with:
      #     # 注意替换为你的 GitHub 源仓库地址
      #     source-repo: git@github.com:EvanHongYousan/EvanHongYousan.github.io.git
      #     # 注意替换为你的 Gitee 目标仓库地址
      #     destination-repo: git@gitee.com:EvanHongYousan/EvanHongYousan.git

      # - name: Build Gitee Page
      #   uses: yanglbme/gitee-pages-action@main
      #   with:
      #     # 注意替换为你的 Gitee 用户名
      #     gitee-username: EvanHongYousan
      #     # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
      #     gitee-password: ${{ secrets.GITEE_PASSWORD }}
      #     # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
      #     gitee-repo: EvanHongYousan/EvanHongYousan
      #     # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
      #     branch: master
